### ISSUE TITLE
ForkTsCheckerWepackPlugin error when upgrading to version 2.0.0

### ISSUE THREAD

**Issue by jsbroks** [nuxt/typescript#403]
**Describe the bug**
Upgraded from 1.0.3 to 2.0.0.

**Error**
```

   ╭─────────────────────────────────────────╮
   │                                         │
   │   Nuxt.js @ v2.13.4-26568025.4da7fb6e   │
   │                                         │
   │   ▸ Environment: development            │
   │   ▸ Rendering:   server-side            │
   │   ▸ Target:      server                 │
   │                                         │
   │   Listening: http://localhost:3000/     │
   │                                         │
   ╰─────────────────────────────────────────╯

ℹ Preparing project for development                                                                                              18:03:25
ℹ Initial build may take a while                                                                                                 18:03:25
✔ Builder initialized                                                                                                            18:03:25
✔ Nuxt files generated                                                                                                           18:03:25

 ERROR  ForkTsCheckerWebpackPlugin Invalid Options                                                                               18:03:27

options.eslint should be object


  
  options.eslint should be object
  
  at Object.validateOptions [as default] (node_modules/fork-ts-checker-webpack-plugin/node_modules/schema-utils/src/validateOptions.js:32:11)
  at new ForkTsCheckerWebpackPlugin (node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.js:28:31)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/typescript-build/dist/index.js:41:33)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils-edge/dist/utils.js:1843:25)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils-edge/dist/utils.js:1838:27)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils-edge/dist/utils.js:1838:27)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils-edge/dist/utils.js:1838:27)
  at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack-edge/dist/webpack.js:4831:37)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack-edge/dist/webpack.js:4866:45)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack-edge/dist/webpack.js:5064:26)
  at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack-edge/dist/webpack.js:5372:19)
  at WebpackBundler.build (node_modules/@nuxt/webpack-edge/dist/webpack.js:5379:12)
  at Builder.build (node_modules/@nuxt/builder-edge/dist/builder.js:5629:30)
  at async Object._buildDev (node_modules/@nuxt/cli-edge/dist/cli-dev.js:102:5)
  at async Object.startDev (node_modules/@nuxt/cli-edge/dist/cli-dev.js:60:7)
  at async Object.run (node_modules/@nuxt/cli-edge/dist/cli-dev.js:47:5)
```

**Comment by kevinmarrec** [comment]
https://github.com/nuxt/typescript/releases/tag/%40nuxt%2Ftypescript-build%402.0.0 Such error is normal cause you need to change options

Please look release notes when upgrading to major versions to see breaking changes

**Comment by jsbroks** [comment]
Thanks, sorry about that.

For others:

Changed:
```
  typescript: {
    typeCheck: {
      eslint: true
    }
  }
```
to
```
  typescript: {
    typeCheck: {
      eslint: {
        enabled: true
      }
    }
  }
```
in `nuxt.config.js`

**Comment by lephuongbg** [comment]
@kevinmarrec Mine doesn't have the typescript option inside nuxt.config.js but is still getting this error.

**Comment by markhughes** [comment]
You can downgrade from 5 to 4 which resolve my issues, I don't understand fully what was happening.

I didn't have a `.nuxt` directory but after clearing `node_modules` and my `dist` directory, I had no luck - as I have an alternative method of SSR so I could use Nest and Nuxt as a monorepo. 

```bash
npm install fork-ts-checker-webpack-plugin@4
```

Here was my log for nuxt ^2.14.0 - hope it helps someone.

```
> tsc -p tsconfig.json && nuxt-ts build

ℹ Production build                                                                                                                                      18:17:20
ℹ Bundling for server and client side                                                                                                                   18:17:20
ℹ Target: server                                                                                                                                        18:17:20
✔ Builder initialized                                                                                                                                   18:17:20
✔ Nuxt files generated                                                                                                                                  18:17:20

 FATAL  ForkTsCheckerWebpackPlugin Invalid Options                                                                                                      18:17:20

options should NOT have additional properties
options should NOT have additional properties


  
  options should NOT have additional properties
  options should NOT have additional properties
  
  at Object.validateOptions [as default] (node_modules/fork-ts-checker-webpack-plugin/node_modules/schema-utils/src/validateOptions.js:32:11)
  at new ForkTsCheckerWebpackPlugin (node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.js:28:31)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/typescript-build/src/index.ts:77:28)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1860:25)
  at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:4863:37)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4898:45)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:5098:26)
  at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:5406:19)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5413:12)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5629:30)
  at Object.run (node_modules/@nuxt/cli/dist/cli-build.js:107:7)
  at NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2798:7)


   ╭─────────────────────────────────────────────────────────────────╮
   │                                                                 │
   │   ✖ Nuxt Fatal Error                                            │
   │                                                                 │
   │   ValidationError: ForkTsCheckerWebpackPlugin Invalid Options   │
   │                                                                 │
   │   options should NOT have additional properties                 │
   │   options should NOT have additional properties                 │
   │                                                                 │
   │                                                                 │
   ╰─────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
```

**Comment by kevinmarrec** [comment]
@markhughes It's cause v5 use different options than v4, and they added options validation, which means that if you didn't migrate correctly (they explain options breaking changes in their release notes, and you can re-check options in their main page), it will make fail options validation, and that's what `options should NOT have additional properties` means.

**Comment by markhughes** [comment]
@kevinmarrec I have no options specified though.

**Comment by kevinmarrec** [comment]
@markhughes Provide me a repository with reproduction of your issue ans I'll be glad to help :)

**Comment by wwwikies** [comment]
+1 ,same error!
error info:
```
(node:35790) UnhandledPromiseRejectionWarning: ValidationError: Invalid configuration object. ForkTsCheckerWebpackPlugin has been initialized using a configuration object that does not match the API schema.
 - configuration.eslint misses the property 'files'. Should be:
   [string, ...] (should not have fewer than 1 item, should not have duplicate items) | string
   -> List of glob patterns or files to be linted.
```
package.json
```
    "@nuxt/typescript-runtime": "^2.0.1",
    "@nuxt/types": "^2.14.12",
    "@nuxt/typescript-build": "^2.0.4",
```
 package-lock.json
```
    "@nuxt/typescript-build": {
      "version": "2.0.4",
      ...
      "requires": {
        "consola": "^2.15.0",
        "fork-ts-checker-webpack-plugin": "^6.1.0",
        "ts-loader": "^8.0.14",
        "typescript": "~4.1"
      }
    },
```
