### ISSUE TITLE
Dependencies not declared

### ISSUE THREAD

**Issue by robcresswell** [nuxt/typescript#408]
**Describe the bug**
Runtime has dependencies that not declared

https://github.com/nuxt/typescript/blob/master/packages/typescript-runtime/bin/nuxt-ts.js

Both `@nuxt/cli` and `@nuxt/cli-edge` are not declared as dependencies; is this intended?

**Comment by IGassmann** [comment]
Probably due to this, on Yarn 2.1.1 building the app causes the following error:

```
/usr/src/app/.pnp.js:22980
    throw firstError;
    ^

Error: @nuxt/typescript-runtime tried to access @nuxt/cli-edge, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @nuxt/cli-edge (via "@nuxt/cli-edge")
Required by: @nuxt/typescript-runtime@virtual:2ed6d5b8a0e51a41ec59e92da8badd9fc2ac235899b8aaf34d8b8c4b8fee22103d8b4ed4d7c1bc2c35b4605ba1f161b2fedfd2007831c533310a955a7f272157#npm:1.0.0 (via /usr/src/app/.yarn/$$virtual/@nuxt-typescript-runtime-virtual-5454485d69/0/cache/@nuxt-typescript-runtime-npm-1.0.0-6641a9e711-ea13884f02.zip/node_modules/@nuxt/typescript-runtime/bin/)

Require stack:
- /usr/src/app/.yarn/$$virtual/@nuxt-typescript-runtime-virtual-5454485d69/0/cache/@nuxt-typescript-runtime-npm-1.0.0-6641a9e711-ea13884f02.zip/node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js
    at internalTools_makeError (/usr/src/app/.pnp.js:22725:34)
    at resolveToUnqualified (/usr/src/app/.pnp.js:23658:21)
    at resolveRequest (/usr/src/app/.pnp.js:23744:29)
    at Object.resolveRequest (/usr/src/app/.pnp.js:23810:26)
    at Function.external_module_.Module._resolveFilename (/usr/src/app/.pnp.js:22957:34)
    at Function.external_module_.Module._load (/usr/src/app/.pnp.js:22821:48)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /usr/src/app/.yarn/$$virtual/@nuxt-typescript-runtime-virtual-5454485d69/0/cache/@nuxt-typescript-runtime-npm-1.0.0-6641a9e711-ea13884f02.zip/node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js:3:79
    at Object.<anonymous> (/usr/src/app/.yarn/$$virtual/@nuxt-typescript-runtime-virtual-5454485d69/0/cache/@nuxt-typescript-runtime-npm-1.0.0-6641a9e711-ea13884f02.zip/node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js:3:109)
```

**Comment by kevinmarrec** [comment]
@robcresswell You're simply supposed to only use this module while using `nuxt` or `nuxt-edge` which install these dependencies. And as we can't know which one users are using, we can't make them peerDepedencies.

@IGassmann I'm not using Yarn 2 cause Yarn 1 is still better in stability from my perspective

**Comment by robcresswell** [comment]
That's a shame, I was hoping to use Vue again, but having to swap package package manager will be a blocker.

**Comment by IGassmann** [comment]
`nuxt` is installed. I guess this might be occurring only with Yarn 2.

**Comment by robcresswell** [comment]
Indeed, Yarn 2 flags it because it's an undeclared dependency.

**Comment by abdelba** [comment]
For those having the issue, the solution is simply to run

    yarn add @nuxt/cli

**Comment by pi0** [comment]
Notice for 2.15+: typescript-runtime (nuxt-ts) is not required anymore since nuxt supports runtime out of the box

**Comment by robcresswell** [comment]
@abdelba I don't believe that solves the issue. Yarn 2 would still flag this is as a problem.
