### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by transtone** [nuxt/typescript#420]
**Describe the bug**
build nuxt spa with    "@nuxt/typescript-build": "^2.0.0"

**To Reproduce**
1. Clone repository '...'
2. Run 'npm run build'
3. See error

**Expected behavior**

**Screenshots**
```shell
✔ Nuxt files generated

 FATAL  The 'request' argument must be string. Received type undefined

  at node_modules/esm/esm.js:1:224803
  at Object.<anonymous> (node_modules/esm/esm.js:1:251922)
  at Object.t (node_modules/esm/esm.js:1:279775)
  at n (node_modules/esm/esm.js:1:279589)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/typescript-build/src/index.ts:76:42)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1843:25)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1838:27)
  at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:4831:37)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4866:45)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:5053:26)
  at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:5361:19)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5368:12)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5629:30)
  at Generator.initiate (node_modules/@nuxt/generator/dist/generator.js:147:7)
  at Generator.generate (node_modules/@nuxt/generator/dist/generator.js:109:5)
  at Object.run (node_modules/@nuxt/cli/dist/cli-build.js:103:7)

^[[43;165R
   ╭───────────────────────────────────────────────────────────────────────────────╮
   │                                                                               │
   │   ✖ Nuxt Fatal Error                                                          │
   │                                                                               │
   │   TypeError: The 'request' argument must be string. Received type undefined   │
   │                                                                               │
   ╰───────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rbs-pc@2.0.0 build: `nuxt-ts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rbs-pc@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-30T08_29_03_518Z-debug.log
```

**Additional context**

**Comment by kevinmarrec** [comment]
See : https://github.com/nuxt/typescript/issues/102

Clear your `node_modules` and remove `package.lock.json`, then do `npm install` and `nuxt-ts build`.

If you still have the issue afterwards, please provide a repository where it's reproducible.

**Comment by transtone** [comment]
> @transtone
> 
> See : #102
> 
> Clear your `node_modules` and remove `package.lock.json`, then do `npm install` and `nuxt-ts build`.
> 
> If you still have the issue afterwards, please provide a repository where it's reproducible.

thinks.
but remove  `node_modules` and `package-lock.json` can't solve the problem.

finally I use `yarn && yarn build`, it works.
