### ISSUE TITLE
Error: Support for the experimental syntax 'decorators-legacy' isn't currently enabled

### ISSUE THREAD

**Issue by tobiasdiez** [nuxt/typescript#494]
**Describe the bug**
Using decorators in the middleware results in the following error:
````
 ERROR  ServerMiddleware Error: ParseError: D:\: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (21:1):                       03:07:09  


 D:\Programming\JabRefOnline\api\index.ts:21:0



  api\index.ts:21:0
  at Resolver.requireModule (node_modules\@nuxt\core\dist\core.js:381:29)
  at Server._requireMiddleware (node_modules\@nuxt\server\dist\server.js:831:39)
  at Server._normalizeMiddleware (node_modules\@nuxt\server\dist\server.js:800:38)
  at Server.resolveMiddleware (node_modules\@nuxt\server\dist\server.js:851:23)
  at Server.useMiddleware (node_modules\@nuxt\server\dist\server.js:880:36)
  at Server.setupMiddleware (node_modules\@nuxt\server\dist\server.js:710:12)
  at processTicksAndRejections (node:internal/process/task_queues:93:5)
  at async Server.ready (node_modules\@nuxt\server\dist\server.js:641:5)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:482:7)
````

**To Reproduce**
1. Use the following code in the file specified as `serverMiddleware`:
```
import 'reflect-metadata'
import { container, injectable, instanceCachingFactory } from 'tsyringe'

@injectable()
class Foo {
  constructor (private database: User) {}
}
```
2. Run `nuxt`
3. See error

**Expected behavior**
No error.

**Screenshots**

**Additional context**
I tried to add various options in build > babel, e.g. using `['@babel/plugin-proposal-decorators', { legacy: true }]` which was recommended in similar instances.

**Comment by tobiasdiez** [comment]
As recommended in https://qiita.com/grainrigi/items/64b4eb316c8d94d0f011, I tried to set `createRequire: 'native'`. But this then leads to yet another error:
````
 ERROR  ServerMiddleware Error: Cannot use import statement outside a module                                                                                                                                                      

  (function (exports, require, module, __filename, __dirname) { import express from 'express'
  ^^^^^^

  SyntaxError: Cannot use import statement outside a module
  at new Script (node:vm:101:7)
  at p._moduleCompile (node_modules\jiti\dist\v8cache.js:2:3031)
  at Module.o._compile (node_modules\jiti\dist\v8cache.js:2:2582)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
  at Module.load (node:internal/modules/cjs/loader:967:32)
  at Function.Module._load (node:internal/modules/cjs/loader:807:14)
  at Module.require (node:internal/modules/cjs/loader:991:19)
  at Resolver.require [as _require] (node:internal/modules/cjs/helpers:92:18)
  at Resolver.requireModule (node_modules\@nuxt\core\dist\core.js:381:29)
  at Server._requireMiddleware (node_modules\@nuxt\server\dist\server.js:831:39)
````

**Comment by jeffborg** [comment]
I've got around this by overriding 1 function from jiti via nuxt.config

I've added the necessary babel bits to support metadata and property decorators

```js
  createRequire: (jsFileName: string) => {
    return jiti(jsFileName, {
      debug: true,
      legacy: true,
      transform (opts: any): any {
        const _opts = {
          babelrc: false,
          configFile: false,
          compact: false,
          retainLines:
            typeof opts.retainLines === 'boolean' ? opts.retainLines : true,
          filename: '',
          cwd: '/',
          plugins: [
            [
              require('@babel/plugin-transform-modules-commonjs'),
              { allowTopLevelThis: true }
            ],
            [require('babel-plugin-transform-typescript-metadata')],
            [require('babel-plugin-dynamic-import-node'), { noInterop: true }],
            [require('babel-plugin-transform-import-meta')],
            [require('@babel/plugin-proposal-decorators'), { legacy: true }],
            [require('@babel/plugin-syntax-class-properties'), { loose: true }]
          ]
        }

        if (opts.ts) {
          _opts.plugins!.push(require('@babel/plugin-transform-typescript'))
        }

        if (opts.legacy) {
          _opts.plugins!.push(
            require('@babel/plugin-proposal-nullish-coalescing-operator')
          )
          _opts.plugins!.push(
            require('@babel/plugin-proposal-optional-chaining')
          )
        }

        try {
          return {
            code: transformSync(opts.source, _opts)?.code || ''
          }
        } catch (err) {
          return {
            error: err,
            code:
              'exports.__JITI_ERROR__ = ' +
              JSON.stringify({
                filename: opts.filename,
                line: err.loc?.line || 0,
                column: err.loc?.column || 0,
                code: err.code
                  ?.replace('BABEL_', '')
                  .replace('PARSE_ERROR', 'ParseError'),
                message: err.message
                  ?.replace('/: ', '')
                  .replace(/\(.+\)\s*$/, '')
              })
          }
        }
      }
    })
  },

```

**Comment by kukosek** [comment]
having the same issue. I just wanna use type-graphql in my server middleware!

**Comment by tobiasdiez** [comment]
Thanks a lot @jeffborg! That worked really well. May I suggest you open a PR to the jiti repo with this fix?

**Comment by dzcpy** [comment]
So what is the best way to fix this?

**Comment by jeffborg** [comment]
@dzcpy I think it needs 2 parts for a proper fix

 - in jiti the ability to specify the babel plugins to use overriding it's hard coded babel plugin list
 - in nuxtjs to take it's babel config (wherever webpack gets that from) and apply this to jiti

What I have done here is to override the entire `createRequire` copying the code from nuxt and then copying the code from jiti and combining it together to get the result I want.

**Comment by izure1** [comment]
I have the same issue.
Using the parameter decolator causes problems.

I'm using `type-graphql`, and below is an error message.

```
Decorating class property failed.
Please ensure that proposal-class-properties is enabled and runs after the decorators transform.
```

**Comment by qwexvf** [comment]
Having same error using the TypeOrm.

**Comment by rchl** [comment]
Since `@nuxt/typescript-runtime` is no longer recommended for latest Nuxt 2 versions because it have built-in support through `jiti`, this is not something that can be fixed here. Feel free to report Nuxt 2 issue if there isn't one already.
