### ISSUE TITLE
Cannot use nuxt head method

### ISSUE THREAD

**Issue by axelthat2** [nuxt/typescript#525]
**Describe the bug**
So when I use `head` method, I get this error,

```
ERROR in pages/index.vue:18:19
TS2339: Property 'blog' does not exist on type 'CombinedVueInstance<Vue, unknown, unknown, unknown, Readonly<Record<never, any>>>'.
    16 |   head() {
    17 |     return {
  > 18 |       title: this.blog.title
       |                   ^^^^
    19 |     }
    20 |   }
    21 | })

 FATAL  Nuxt build error                                               10:47:29

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:110:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯
```

**To Reproduce**
1. Goto: https://codesandbox.io/s/pedantic-burnell-p2c7l
2. Then in terminal, run `yarn build`.

**Comment by rchl** [comment]
Closing due to lack of response.
