### ISSUE TITLE
Optional Chaining and Nullish Coalescing works on `<script>` but not in `<template>`

### ISSUE THREAD

**Issue by ewilan-riviere** [nuxt/typescript#533]
- OS: Windows 10
- Node.js: v16.13.0
- Yarn: 1.2
- Nuxt: v2.15.8
- @nuxt/typescript-build: v2.1.0

**Describe the bug**

[Optional Chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) and [Nullish Coalescing](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) works on `<script>` but not in `<template>`.

Here an example with `Book` interface where `cover` is null safety with `thumbnail` also null safety.

```ts
// @/types/book.ts
export interface Cover {
  thumbnail?: string
  simple?: string
  color?: string
}

export interface Book {
  title: string
  meta: BookMeta
  authors?: Author[]
  summary: string
  language: string
  publishDate?: Date
  cover?: Cover
  volume: number
  serie: Serie
}
```

When I request API, I can use option chaining in `<script>` like in *return* of *asyncData*, in `<template>` I've have to use `v-if` on `<img />` because `cover` can be null.

```vue
<template>
    <div>
        <div v-for="(book, index) in books" :key="index">
            <img v-if="book.cover" :src="book.cover.thumbnail" :alt="book.title" />
        </div>
    </div>
</template>

<script lang="ts">
import { ApiPaginateResponse, Book } from '~/types'

const books = ref<Book[]>()

export default {
    async asyncData (ctx: any): Promise<object> {
        try {
            const response: ApiPaginateResponse = await ctx.$axios.$get(
                `https://bookshelves.ink/api/books?per-page=32`
            )

            return {
                books: response.data,
                pages: response.meta?.last_page,
                currentPage: response.meta?.current_page,
                perPage: response.meta?.per_page,
                total: response.meta?.total
            }
        } catch (error) {
            console.error(error)
            return {
                books: []
            }
        }
    }
}
</script>
```

If I use optional chaining in `<template>`, I've an error

```vue
<img :src="book.cover?.thumbnail" :alt="book.title" />
```

```bash
ERROR in ./pages/composition-api/labs.vue?vue&type=template&id=42ad4517& (./node_modules/unplugin/dist/webpack/loaders/transform.js??ref--16-0!./node_modules/windicss-webpack-plugin/dist/loaders/pitcher.js!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/windicss-webpack-plugin/dist/loaders/transform-template.js!./node_modules/unplugin/dist/webpack/loaders/transform.js??ref--17-0!./node_modules/unplugin/dist/webpack/loaders/transform.js??ref--18-0!./pages/composition-api/labs.vue?vue&type=template&id=42ad4517&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
SyntaxError: Unexpected token (1:527)
    at Parser.pp$4.raise (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:2757:13)
    at Parser.pp.unexpected (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:647:8)
    at Parser.pp$3.parseExprAtom (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:2196:10)
    at Parser.<anonymous> (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:6003:24)
    at Parser.parseExprAtom (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:6129:31)
    at Parser.pp$3.parseExprSubscripts (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:2024:17)
    at Parser.pp$3.parseExprOps (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:1925:19)
    at Parser.pp$3.parseMaybeConditional (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:1954:28)
    at Parser.pp$3.parseMaybeAssign (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:1925:19)
    at Parser.pp$3.parsePropertyValue (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:2443:87)
    at Parser.pp$3.parseProperty (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:2434:8)
    at Parser.pp$3.parseObj (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:2380:23)
    at Parser.pp$3.parseExprAtom (C:\workspace\projets\nuxt-typescript-template\node_modules\vue-template-es2015-compiler\buble.js:2179:17)
```

**To Reproduce**

- [CodeSandbox](https://codesandbox.io/s/nuxt-ts-optional-chaining-rs7ml)
- [GitLab repository](https://gitlab.com/ewilan-riviere/nuxt-typescript-template)

1. `git clone git@gitlab.com:ewilan-riviere/nuxt-typescript-template.git`
2. `yarn`
3. `yarn dev`
4. Go to <http://localhost:3000>
3. See error

**Expected behavior**

I would to use optional chaining into `<template>`.

**Screenshots**

![nuxt-ts-error](https://user-images.githubusercontent.com/48261459/143778873-46036a5e-112d-48b3-8c82-c90708b5c1b4.jpg)

**Comment by ewilan-riviere** [comment]
Ok, I found a solution from Stackoverflow [*Support optional chaining in vuejs*](https://stackoverflow.com/questions/61770909/support-optional-chaining-in-vuejs)

```bash
yarn add vue-template-babel-compiler -D # npm install vue-template-babel-compiler --save-dev
```

In my `nuxt.config.ts`

```
import type { NuxtConfig } from '@nuxt/types'

const config: NuxtConfig = {
  // https://nuxtjs.org/docs/configuration-glossary/configuration-build
  build: {
    loaders: {
      vue: {
        compiler: require('vue-template-babel-compiler')
      }
    }
  }
  // ...
}

export default config
```

An now *option chaining* works with Typescript.
