### ISSUE TITLE
typescript-runtime: setupTSConfig is not a function

### ISSUE THREAD

**Issue by Sylor73** [nuxt/typescript#57]
**Describe the bug**
Doesn't work typescript-runtime library.
Error
```
 ERROR  setupTSConfig is not a function                                                                                                                                                          11:49:03

  at main (node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js:10:9)
  at Object.<anonymous> (node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js:17:1)
  at Module._compile (internal/modules/cjs/loader.js:736:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
  at Module.load (internal/modules/cjs/loader.js:628:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
  at Function.Module._load (internal/modules/cjs/loader.js:560:3)
  at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
  at executeUserCode (internal/bootstrap/node.js:526:15)
  at startMainThreadExecution (internal/bootstrap/node.js:439:3)
```

**To Reproduce**
1. Open https://typescript.nuxtjs.org/guide/runtime.html#installation
2. Complete all steps
3. Execute `npm run build`

**Expected behavior**
Project's build will be successfully complete.

**Additional context**
I looked in the library's source and I can't find out module which export setupTSConfig function.

**Comment by kevinmarrec** [comment]
@Sylor73 You're right, it's something that has been removed lately.
Releasing a fix asap

**Comment by Sylor73** [comment]
Thanks, nice work!

**Comment by kevinmarrec** [comment]
@Sylor73 Fixed and release
https://github.com/nuxt/typescript/releases
